#!/bin/sh

git submodule foreach git pull origin main

find .git/hooks -type l -exec rm {} \;
find .githooks/src -type f -exec ln -sf ../../{} .git/hooks/ \;
find .git/hooks -type l -exec chmod +x {} \;
