#!/bin/bash
#
# This hook script verifies that commit message is in valid format.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
source ./.githooks/src/utility/vars
source ./.githooks/src/utility/functions

echo "Checking commit message format..."

check_pattern "$VALID_COMMIT_REGEX" "$(cat "$1")" "Commit message"
