#!/bin/bash
#
# This hook script verifies that branch name is in valid format.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
source ./.githooks/src/utility/vars
source ./.githooks/src/utility/functions

echo "Checking branch name format..."

check_pattern "$VALID_BRANCH_REGEX" "$(git rev-parse --abbrev-ref HEAD)" "Branch name"
