#!/bin/sh
#
# This hook script holds allowed branches prefixes
# and regular expression patterns for checking branches and commit messages
#
ALLOWED_PREFIX_TYPES="feat|chore|fix|spike"

VALID_COMMIT_REGEX="^($ALLOWED_PREFIX_TYPES)\([A-Z]+-[0-9]+\):[@/#&*%,.=+-_a-zA-Z0-9 ]+$"
TASK_ID_IN_COMMIT_REGEX="^($ALLOWED_PREFIX_TYPES)\([A-Z]+-[0-9]+\)+"

VALID_BRANCH_REGEX="^($ALLOWED_PREFIX_TYPES)\/[A-Z]+-[0-9]+\/[a-zA-Z0-9-]+$"
TASK_ID_IN_BRANCH_REGEX="^($ALLOWED_PREFIX_TYPES)\/[A-Z]+-[0-9]+\/+"