#!/bin/sh
#
# This hook script verifies that branch name is in valid format.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#

echo "Checking branch name format..."

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
VALID_BRANCH_REGEX="^(feat|chore|fix|spike)\/[A-Z]+-[0-9]+\/[a-zA-Z0-9-]+$"

if ! [[ "$BRANCH_NAME" =~ $VALID_BRANCH_REGEX ]]
then
  echo "Your branch name is not valid: $BRANCH_NAME"
  echo "Branch name must match pattern: $VALID_BRANCH_REGEX"

  exit 1
fi
